### ISSUE TITLE
Создание модели базы данных

### ISSUE THREAD

**Issue by anastasiski** [ochenmudro/quizia#1]
Необходимо создать **модель базы данных** разрабаотываемой системы, лучше все посредством спеиальной IDE, предоставляемой СУБД (например MySql Workbench):

- [x] Для этого понадобится установить сам сервер, скачать можно [отсюда](https://dev.mysql.com/downloads/installer/), вот [тут](https://wiki.merionet.ru/servernye-resheniya/12/ustanovka-mysql-servera-na-windows-10/) есть неплохая инструкция по установке

- [x] Скачать сам Workbench можно [отсюда](https://dev.mysql.com/downloads/workbench/)

- [x] Интерфейс там совсем несложный, создать новую схему, в ней таблицы и связи между ними, также определиться с типами хранимых данных и их размером

- [x] Созданную схему удобно сохранить в .mwb формте, так ее проще просмотреть, а так же на ее основании можно сгенерировать саму бд без неоходимости писать SQL запросы

- [x] Схему мужно загрузить сюда как решение задачи

P.S. выбрать СУБД и программы для разработки модели можно абсолютно любую

**Comment by anastasiski** [comment]
![image](https://user-images.githubusercontent.com/56916616/139645670-588d7934-593b-42ad-bb34-8b499c4465f1.png)
![image](https://user-images.githubusercontent.com/56916616/139645751-df8aa5d4-5417-42b8-899d-dab1b4522184.png)
![image](https://user-images.githubusercontent.com/56916616/139645949-77a3700a-ccf6-461a-b0ae-ca798a3d2f9b.png)
![image](https://user-images.githubusercontent.com/56916616/139645984-f6abb3b5-5a0b-4fba-8252-65430b9ec973.png)
![image](https://user-images.githubusercontent.com/56916616/139646017-48e00b93-192e-42ce-a25e-2c2243ffb4e4.png)
![image](https://user-images.githubusercontent.com/56916616/139646080-b4256fdf-097a-4209-9676-d622487ded40.png)

**Comment by ochenmudro** [comment]
[DBmodel.zip](https://github.com/ochenmudro/quizia/files/7473030/DBmodel.zip)
@anastasiski

**Comment by anastasiski** [comment]
Очень хорошая работа, все выглядит логично и продуманно!

Какие на данный момент есть проблемы:
1. База данных у нас все же реляционная, но сущность User у нас ни с чем не связана. Это омжет не быть ошибкой, но тогда надо задуматься. а зачем нам тогда пользователь вообще нужен. Если я могу пройти тест не регистрируясь, а могу зарегистроваться и пройти, но никаких дополнителных возможостей мне это не дает, зачем я буду регистрироваться? Стоит подумать над тем, какие дополнительные штуки может делать зарегистрированный пользоватьель, например, может быть, у него будет доступ к своей истории, какие он проходил уже тесты, сколько баллов набрал и т.д. Таким образом, у него появится связь с другими таблицами.
2. Стоит также подумать над форматтами твоих ответов. Если это только вопросы с вариантами ответа, то вариант как сейчас вполне подходит, разве что можно добавить какой-нибудь дополнительный булевый признак в вопрос, который бы указывал, поддерживает ли он множественные варианты ответа. Если предполагается, что будут возможно вопросы без вариантов ответка, куда пользователь сам пишет текст, стоит подумать над тем, как это организовать. Но, вполне возможно, это излишне, это только твое решение.
3. Так же можно подумаь на счет введения в Вопрос дополнительного поля "Баллы", потому что все же вопросы могут быть разной сложности, но это опять же по желанию
4. Так же еще могу предложить подумать над тем. чтобы ввести дополнительную таблицу "Категория" и связать ее с тестом, так будет проще сортировать и искать нужный

Из сеьезно проьблемного только 1, остальное скорее опционально:)

**Comment by ochenmudro** [comment]
[DBmodel.zip](https://github.com/ochenmudro/quizia/files/7510293/DBmodel.zip)

**Comment by anastasiski** [comment]
![image](https://user-images.githubusercontent.com/56916616/141087162-876295f9-9ff9-4d13-9635-3d2296de5199.png)
Уже очень похоже на правду!
Что осталось доработать:
1. У нас почему-то потерялась связь между вопросом и тестом:(
2. Насколько нам нужно выносить Результат в отдельную таблицу? Ведь наша история как раз и отражает результат, он вряд-ли будет дублироваться, скорее будет своим и уникальным для этого пользователя. Поэтому, возможно. поля из этой таблицы следует поместить в саму таблицу Истории, чтобы у нас там был айдишник пользователя, теста, и его результаты: количество баллов, может быть время выполнения и другие поля, какие ты зпхочешь туда добавить.
3. Тип для баллов ты выбрала INT, подойдет, если ты хорошо продумала, как буду начисляться баллы. Например, если есть вопрос с множественными ответами, как в таком случае считать балл - давать за вопрос не 1 балл, а столько, сколько правильных ответов? Или давать балл только если выбраны все правильные? Потому что если ты решишь засчитывать частично и начнется деление баллов в зависимости от того, сколько правильных ответов выбрано - нужно брать дробный тип. Тут нет правильного ответа, все тольео на твое усмотрение, как ты захочешь это рнализовать, главное - определиться.
4. Поле "правильности" в ответе у тебя почему-то текствое, но ведь наш ответ может быть или правильным или нет, возможно стоит обратить внимание на булевый тип

Так держать, идем к успеху!

**Comment by ochenmudro** [comment]
[DBmodel.zip](https://github.com/ochenmudro/quizia/files/7518584/DBmodel.zip)
Я подумала пока сделать простые тесты с одним вариантом ответа, а если этот курсач выведется потом на диплом, можно будет всё интереснее приделать

**Comment by anastasiski** [comment]
Ну что, последние шаги!

1. Что планируется писать в описании к таблице история?  Это какое-то уникальное сообщение? Если нет, его можно просто захардкодить на UI и нет смысла хранить, если да - то пусть остается
2. Таблички по конвенции лучше называть в единственном числе:)

Больше можешь не кидать, исправь то, что нужно и можешь закрывать задачу.
Если что, будем редактировать в процессе;)
