### ISSUE TITLE
Взаимодействие с БД через IntelliJ Idea

### ISSUE THREAD

**Issue by anastasiski** [ochenmudro/quizia#6]
Тебе будет намного комфортнее работать, если ты подтянешь свою бд в идею
Как это сделать?

Я оставлю краткое описание, если  с чем-то возникнут проблемы - спрашивай:)

![image](https://user-images.githubusercontent.com/56916616/141448509-2590342d-62d9-458d-b034-9eca77615ad9.png)
![image](https://user-images.githubusercontent.com/56916616/141448566-a9864498-d6df-4b22-919a-5da6ccf723cb.png)
![image](https://user-images.githubusercontent.com/56916616/141448607-8ca05aa4-d7fd-44b5-ae38-9ab2e798e0ab.png)

По умолчанию сервер бд крутится на 3306 порту, если ты ничего не меняла, то достаточно через / указать имя бд + логин и пароль с помощью которого ты входишь в WorkBench

![image](https://user-images.githubusercontent.com/56916616/141449100-44518832-868f-4320-8818-56417fa1fdd0.png)

**Comment by ochenmudro** [comment]
![photo_2021-11-12_14-51-21](https://user-images.githubusercontent.com/43651215/141463605-17346fb3-b7b8-422d-a256-55113fde3bb0.jpg)

У меня IJ comunity и я делаю через плагин DB Navigator
Выскакивает при подключении такая ошибка, и по сути нужно исправить JDBC  но у меня его пока нет, насколько я поняла. Его нужно создать и прописать там TimeZone?

**Comment by anastasiski** [comment]
Попробуй указать таймзону явно в строке подключения, это будет выглядеть как-то так:
jdbc:mysql://localhost/quizia?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC

**Comment by ochenmudro** [comment]
Господи, впервые в жизни у меня получилось подключить БД!
